CREATE TABLE IF NOT EXISTS contentCreators (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  state ENUM('online', 'offline', 'stuck') NOT NULL DEFAULT 'offline',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
