CREATE TABLE IF NOT EXISTS contentCreators (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  managerID VARCHAR(36) NULL,
  state ENUM('online', 'offline', 'stuck') NOT NULL DEFAULT 'offline',
  FOREIGN KEY (managerID) REFERENCES managers(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_managerID (managerID)
);
