CREATE TABLE IF NOT EXISTS videos (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  editorID VARCHAR(36) NULL,
  state ENUM('notStarted', 'workingOn', 'completed', 'posted') NOT NULL DEFAULT 'notStarted',
  FOREIGN KEY (editorID) REFERENCES editors(id) ON DELETE CASCADE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deletedAt TIMESTAMP NULL DEFAULT NULL,
  INDEX idx_editor (editorID)
);
