CREATE TABLE IF NOT EXISTS accounts (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  contentCreatorID VARCHAR(36) NULL,
  contentDescription TEXT NULL,
  FOREIGN KEY (contentCreatorID) REFERENCES contentCreators(id) ON DELETE CASCADE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deletedAt TIMESTAMP NULL DEFAULT NULL,
  INDEX idx_contentCreator (contentCreatorID)
);
